import { readdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import {
  cutoverScope,
  parseLegacyMemories,
  rollbackScope,
  type CutoverReport,
  type PostgresMemoryStore,
  type RollbackReport,
} from '../../backend/memory/src/index.ts'
import { createServerMemorySession } from './memory-session'
import { legacySourceFor } from './node-memory-integration'

/**
 * Stage 15 migration manifest: which owners move, from which files, with
 * what expected content, and what "done" and "undo" mean. Generated by a dry
 * run that writes nothing; executed owner by owner. No memory text appears
 * in a manifest or a result, only ids, counts, hashes and reasons.
 */

export interface MigrationOwner {
  owner: string
  file: string
  /** Hash of the whole legacy file at planning time; execution refuses a file that changed since. */
  legacyRevision: string
  expectedCount: number
  quarantined: { reason: string; count: number }[]
}

export interface MigrationManifest {
  format: 'gideon-memory-migration'
  version: 1
  environment: string
  createdAt: string
  source: { kind: 'node-json-files'; directory: string }
  destination: { kind: 'postgres'; connection: 'GIDEON_MEMORY_DATABASE_URL' }
  writerFence: string
  owners: MigrationOwner[]
  /** Files whose names are not a signed owner key; never guessed into an account. */
  unrecognizedFiles: string[]
  protectedData: string[]
  rollback: string[]
}

const OWNER_FILE = /^([0-9a-f]{64})\.json$/u

/** Dry run: reads every legacy file and describes the move without writing anything. */
export async function planLegacyMigration(options: { directory: string; environment: string; now?: string }): Promise<MigrationManifest> {
  const directory = resolve(options.directory)
  const previous = process.env.GIDEON_MEMORY_DIR
  process.env.GIDEON_MEMORY_DIR = directory
  try {
    const names = (await readdir(directory).catch((error: { code?: string }) => {
      if (error.code === 'ENOENT') return [] as string[]
      throw error
    })).sort()
    const owners: MigrationOwner[] = []
    const unrecognizedFiles: string[] = []
    for (const name of names) {
      const match = OWNER_FILE.exec(name)
      if (!match) {
        if (!name.endsWith('.tmp')) unrecognizedFiles.push(name)
        continue
      }
      const owner = `node/${match[1]}`
      const parsed = parseLegacyMemories(await legacySourceFor(owner).read())
      const reasons = new Map<string, number>()
      for (const row of parsed.quarantined) reasons.set(row.reason, (reasons.get(row.reason) ?? 0) + 1)
      owners.push({
        owner,
        file: name,
        legacyRevision: parsed.revision,
        expectedCount: parsed.valid.length,
        quarantined: [...reasons].map(([reason, count]) => ({ reason, count })),
      })
    }
    return {
      format: 'gideon-memory-migration',
      version: 1,
      environment: options.environment,
      createdAt: options.now ?? new Date().toISOString(),
      source: { kind: 'node-json-files', directory },
      destination: { kind: 'postgres', connection: 'GIDEON_MEMORY_DATABASE_URL' },
      writerFence: 'gideon_memory.authority_cutovers: compare-and-set per owner under a PostgreSQL advisory lock; HTTP turns and sockets check it on every write',
      owners,
      unrecognizedFiles,
      protectedData: [
        'The legacy files are never deleted by the migration; after cutover they are read-only projections.',
        'Anything forgotten in the new authority is never imported again, including from an older copy of a file.',
        'Quarantined rows stay in the legacy file untouched and are listed here by reason.',
      ],
      rollback: [
        'Per owner: GIDEON_MEMORY_CUTOVER=1 npm run memory:ops -- rollback <legacy-dir> <owner>.',
        'The legacy file is rewritten from the current new-authority projection, keeping corrections and deletions; the pre-migration file is not restored.',
        'Everyone at once: GIDEON_MEMORY_CUTOVER_ENABLED=0 returns routing to the pre-Stage-15 behavior; owners already moved then read the new authority through the flags as before.',
      ],
    }
  } finally {
    if (previous === undefined) delete process.env.GIDEON_MEMORY_DIR
    else process.env.GIDEON_MEMORY_DIR = previous
  }
}

export interface MigrationResult {
  owner: string
  outcome: CutoverReport['outcome'] | 'changed_since_plan' | 'error'
  reason: string | null
  expected: number
  imported: number
  alreadyImported: number
  duplicateText: number
  forgotten: number
  quarantined: number
  deltaRounds: number
}

function operatorSession(owner: string, store: PostgresMemoryStore) {
  return { ...createServerMemorySession({ owner, store, channel: 'worker_http', authority: 'worker_internal_owner' }), store }
}

/**
 * Executes a reviewed manifest owner by owner. An owner whose file changed
 * since planning is skipped with `changed_since_plan`: re-plan and review
 * instead of moving content nobody looked at.
 */
export async function executeLegacyMigration(manifest: MigrationManifest, store: PostgresMemoryStore, options: { owners?: readonly string[]; now?: string } = {}): Promise<MigrationResult[]> {
  if (manifest.format !== 'gideon-memory-migration' || manifest.version !== 1) throw new Error('Not a migration manifest.')
  const previous = process.env.GIDEON_MEMORY_DIR
  process.env.GIDEON_MEMORY_DIR = manifest.source.directory
  try {
    const results: MigrationResult[] = []
    for (const planned of manifest.owners) {
      if (options.owners && !options.owners.includes(planned.owner)) continue
      const empty = { expected: planned.expectedCount, imported: 0, alreadyImported: 0, duplicateText: 0, forgotten: 0, quarantined: 0, deltaRounds: 0 }
      const legacy = legacySourceFor(planned.owner)
      if (parseLegacyMemories(await legacy.read()).revision !== planned.legacyRevision) {
        results.push({ owner: planned.owner, outcome: 'changed_since_plan', reason: 'the file changed after the manifest was made', ...empty })
        continue
      }
      try {
        const report = await cutoverScope(operatorSession(planned.owner, store), legacy, { now: options.now })
        const sum = (key: 'imported' | 'already_imported' | 'duplicate_text' | 'forgotten') => report.imports.reduce((total, item) => total + item.counts[key], 0)
        results.push({
          owner: planned.owner, outcome: report.outcome, reason: report.reason, expected: report.expected,
          imported: sum('imported'), alreadyImported: sum('already_imported'), duplicateText: sum('duplicate_text'), forgotten: sum('forgotten'),
          quarantined: report.quarantined.length, deltaRounds: report.deltaRounds,
        })
      } catch (error) {
        results.push({ owner: planned.owner, outcome: 'error', reason: error instanceof Error ? error.name : 'error', ...empty })
      }
    }
    return results
  } finally {
    if (previous === undefined) delete process.env.GIDEON_MEMORY_DIR
    else process.env.GIDEON_MEMORY_DIR = previous
  }
}

/** Hands one owner back to the legacy file, rewritten from the current projection. */
export async function rollbackLegacyOwner(owner: string, store: PostgresMemoryStore, directory: string): Promise<RollbackReport> {
  const previous = process.env.GIDEON_MEMORY_DIR
  process.env.GIDEON_MEMORY_DIR = directory
  try {
    return await rollbackScope(operatorSession(owner, store), legacySourceFor(owner))
  } finally {
    if (previous === undefined) delete process.env.GIDEON_MEMORY_DIR
    else process.env.GIDEON_MEMORY_DIR = previous
  }
}

/** Which settings are present, as booleans and counts only; never a value. */
export function memoryConfigCheck(env: NodeJS.ProcessEnv = process.env): Record<string, boolean | string> {
  const present = (name: string) => Boolean(env[name]?.trim())
  const on = (name: string) => env[name] === '1'
  return {
    databaseUrlSet: present('GIDEON_MEMORY_DATABASE_URL'),
    identitySecretSet: present('GIDEON_IDENTITY_SECRET'),
    legacyDirectory: env.GIDEON_MEMORY_DIR ? 'set' : 'default (.gideon/memories)',
    captureEnabled: on('GIDEON_MEMORY_CAPTURE_ENABLED'),
    commandWritesEnabled: on('GIDEON_MEMORY_COMMAND_WRITES_ENABLED'),
    recallEnabled: on('GIDEON_MEMORY_RECALL_ENABLED'),
    rolloutPercent: /^\d{1,3}$/u.test(env.GIDEON_MEMORY_ROLLOUT_PERCENT ?? '') ? String(env.GIDEON_MEMORY_ROLLOUT_PERCENT) : '0',
    cutoverRoutingEnabled: on('GIDEON_MEMORY_CUTOVER_ENABLED'),
    backgroundEnabled: on('GIDEON_MEMORY_BACKGROUND_ENABLED'),
    learningEnabled: on('GIDEON_MEMORY_LEARNING_ENABLED'),
    productionCutoverGate: on('GIDEON_MEMORY_STAGE15_CUTOVER'),
    nodeEnv: env.NODE_ENV ?? 'unset',
  }
}
