import type { ConversationState } from '../conversation-state'
import type { MemoryToolRuntime } from '../tools/registry'
import type { ContextPack } from './retrieval'

export interface MemoryRecallTurnContext {
  /** Client request id is correlation only; responseId is generated by server. */
  turnId: string
  responseId: string
  principalId: string
  scopeId: string
  policyEpoch: number
  timezone: string
  latestUserText: string
  transcriptHash: string
  speculative: boolean
  depth?: 'deep'
  conversationState: ConversationState | null
}

export interface MemoryCaptureTurnContext {
  turnId: string
  conversationId: string
  principalId: string
  scopeId: string
  policyEpoch: number
  latestUserText: string
  transcriptHash: string
}

export type MemoryCaptureOutcome =
  | { status: 'captured'; receiptState: 'captured' | 'accepted' | 'indexed' }
  | { status: 'unavailable' | 'failed'; reason: string }

export type MemoryRecallOutcome =
  | { status: 'ready'; binding: MemoryRecallTurnContext; pack: ContextPack }
  /** `temporary`: the owner turned on a temporary conversation; memory is neither read nor written. */
  | { status: 'unavailable'; reason: 'not_configured' | 'unauthorized' | 'timeout' | 'stale' | 'failure' | 'temporary' }

export interface MemoryTurnRuntime extends MemoryToolRuntime {
  captureUserTurn?(
    context: MemoryCaptureTurnContext,
    signal: AbortSignal,
  ): Promise<MemoryCaptureOutcome>
  retrieve(
    query: string,
    context: MemoryRecallTurnContext,
    signal: AbortSignal,
  ): Promise<MemoryRecallOutcome>
}

/** SHA-256 binds speculative retrieval to the exact committed transcript. */
export async function memoryTranscriptHash(text: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text))
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('')
}

export function sameMemoryRecallBinding(
  expected: MemoryRecallTurnContext,
  actual: MemoryRecallTurnContext,
): boolean {
  return expected.turnId === actual.turnId
    && expected.responseId === actual.responseId
    && expected.principalId === actual.principalId
    && expected.scopeId === actual.scopeId
    && expected.policyEpoch === actual.policyEpoch
    && expected.depth === actual.depth
    && expected.transcriptHash === actual.transcriptHash
    && expected.speculative === actual.speculative
    && expected.conversationState?.conversationId === actual.conversationState?.conversationId
}
