/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemCardRouteImport } from './routes/system-card'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabCardsRouteImport } from './routes/lab.cards'
import { Route as ApiVoiceRouteImport } from './routes/api.voice'
import { Route as ApiTranscribeRouteImport } from './routes/api.transcribe'
import { Route as ApiHealthzRouteImport } from './routes/api.healthz'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAccountRouteImport } from './routes/api.account'

const SystemCardRoute = SystemCardRouteImport.update({
  id: '/system-card',
  path: '/system-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCardsRoute = LabCardsRouteImport.update({
  id: '/lab/cards',
  path: '/lab/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/system-card': typeof SystemCardRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/voice': typeof ApiVoiceRoute
  '/lab/cards': typeof LabCardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/system-card': typeof SystemCardRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/voice': typeof ApiVoiceRoute
  '/lab/cards': typeof LabCardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/system-card': typeof SystemCardRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/voice': typeof ApiVoiceRoute
  '/lab/cards': typeof LabCardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/system-card'
    | '/api/account'
    | '/api/chat'
    | '/api/config'
    | '/api/healthz'
    | '/api/transcribe'
    | '/api/voice'
    | '/lab/cards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/system-card'
    | '/api/account'
    | '/api/chat'
    | '/api/config'
    | '/api/healthz'
    | '/api/transcribe'
    | '/api/voice'
    | '/lab/cards'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/system-card'
    | '/api/account'
    | '/api/chat'
    | '/api/config'
    | '/api/healthz'
    | '/api/transcribe'
    | '/api/voice'
    | '/lab/cards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  SystemCardRoute: typeof SystemCardRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  LabCardsRoute: typeof LabCardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-card': {
      id: '/system-card'
      path: '/system-card'
      fullPath: '/system-card'
      preLoaderRoute: typeof SystemCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/cards': {
      id: '/lab/cards'
      path: '/lab/cards'
      fullPath: '/lab/cards'
      preLoaderRoute: typeof LabCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  SystemCardRoute: SystemCardRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  LabCardsRoute: LabCardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
